spring:
  blockscouter:
    # Ethereum chains
    eth:
      chains:
        - chainId: 36435
          blockTime: 5000
          # Subscribe new blocks or not
          subscribeNewBlocks: true
          # Subscribe pending txns or not
          subscribePendingTransactions: true
          # pending tx batch max size to flush
          pendingTxBatchMaxSize: 100
          # pending tx batch max seconds to flush
          pendingTxBatchMaxSeconds: 5

          ######################
          # health check
          health:
            # health check type ["connected", "syncing", "synchronized"]
            type: connected
            # max allowance between current_block and highest block if "sycing" type is provided
            allowance: 0

          ######################
          # nodes
          nodes:
            - name: eth-node1
              rpcUrl: http://localhost:8545
              subscribeBlock: false
              subscribePendingTx: true
              # polling interval to request filter changes in milli seconds
              pendingTxPollingInterval: 1000
            - name: eth-node2
              rpcUrl: ws://localhost:9546
              subscribeBlock: false
              subscribePendingTx: true
              # polling interval to request filter changes in milli seconds
              pendingTxPollingInterval: 1000